metric_categories:
  proc:
    -
      category: PROC_CPU
      metrics:
        - gala_gopher_proc_utime_jiffies
        - gala_gopher_proc_stime_jiffies
    -
      category: PROC_IO_LOAD
      metrics:
        - gala_gopher_proc_read_bytes
        - gala_gopher_proc_write_bytes
      trend: rise
    -
      category: PROC_IO_DELAY
      metrics:
        - gala_gopher_proc_iowait_us
        - gala_gopher_proc_bio_latency
    -
      category: PROC_NET_DELAY
      metrics:
        - gala_gopher_proc_ns_sendmsg
        - gala_gopher_proc_ns_recvmsg
  disk:
    -
      category: DISK_LOAD
      metrics:
        - gala_gopher_disk_rspeed_kB
        - gala_gopher_disk_wspeed_kB
        - gala_gopher_disk_rspeed
        - gala_gopher_disk_wspeed
      trend: rise
    -
      category: DISK_DELAY
      metrics:
        - gala_gopher_disk_r_await
        - gala_gopher_disk_w_await
        - gala_gopher_disk_rareq
        - gala_gopher_disk_wareq
  block:
    -
      category: BLOCK_DELAY
      metrics:
        - gala_gopher_block_latency_req_max
        - gala_gopher_block_latency_req_last
        - gala_gopher_block_latency_req_sum
        - gala_gopher_block_latency_req_jitter
        - gala_gopher_block_count_latency_req
  nic:
    -
      category: NIC_DROP
      metrics:
        - gala_gopher_nic_tc_sent_drop
        - gala_gopher_nic_tx_dropped
        - gala_gopher_nic_rx_dropped
  cpu:
    -
      category: CPU_TOTAL
      metrics:
        - gala_gopher_cpu_total_used_per

infer_rules:
  -
    from_type: cpu
    to_type: proc
    metric_range:
      -
        from: CPU_TOTAL
        to: PROC_CPU
  -
    from_type: block
    to_type: proc
    metric_range:
      -
        from: BLOCK_DELAY
        to: VIRTUAL_IO_DELAY
  -
    from_type: proc
    to_type: disk
    metric_range:
      -
        from: PROC_IO_LOAD
        to: ALL
  -
    from_type: disk
    to_type: block
    metric_range:
      -
        from: DISK_DELAY
        to: BLOCK_DELAY
  -
    from_type: proc
    to_type: sli
    metric_range:
      -
        from: VIRTUAL_IO_DELAY
        to: ALL
      -
        from: PROC_CPU
        to: ALL
cross_rules:
  -
    from_type: disk
    to_type: proc
    metric_range:
      -
        from: DISK_LOAD
        to: PROC_IO_LOAD
      -
        from: DISK_LOAD
        to: VIRTUAL_IO_LOAD
  -
    from_type: proc
    to_type: disk
    metric_range:
      -
        from: PROC_IO_LOAD
        to: ALL
      -
        from: VIRTUAL_IO_LOAD
        to: ALL
  -
    from_type: proc
    to_type: block
    metric_range:
      -
        from: PROC_IO_DELAY
        to: BLOCK_DELAY
      -
        from: VIRTUAL_IO_DELAY
        to: BLOCK_DELAY
  -
    from_type: block
    to_type: proc
    metric_range:
      -
        from: BLOCK_DELAY
        to: VIRTUAL_IO_DELAY
